syntax on
filetype plugin indent on

let mapleader = ","

" Visual mode pressing * or # searches for the current selection -- by Michael Naumann
vnoremap <silent> * :<C-u>call VisualSelection('', '')<CR>/<C-R>=@/<CR><CR>
vnoremap <silent> # :<C-u>call VisualSelection('', '')<CR>?<C-R>=@/<CR><CR>

function! VisualSelection(direction, extra_filter) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", "\\/.*'$^~[]")
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:direction == 'gv'
        call CmdLine("Ack '" . l:pattern . "' " )
    elseif a:direction == 'replace'
        call CmdLine("%s" . '/'. l:pattern . '/')
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction

function! CmdLine(str)
    call feedkeys(":" . a:str)
endfunction

" :W -- use sudo to save the file
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

" Enable mouse support
set mouse=a

" Enable line numbers
set number

" Tab settings
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent