#!/bin/bash
set -e

if [[ -z $1 ]]; then
    echo "Usage: $(basename $0) <CONTAINER_NAME>"
    exit 1
fi

contname=$1
basedir=$(dirname "$(readlink -f "$0")")

(set -x; docker kill $contname)
(set -x; docker rm $contname)
