#!/bin/bash
set -e

if [[ -z $1 ]]; then
    echo "Usage: $(basename $0) <CONTAINER_NAME>"
    exit 1
fi

contname=$1

ip=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $contname)
(set -x; ssh root@$ip)
