#!/bin/bash
set -e

if [[ -z $1 || -z $2 ]]; then
    echo "Usage: $(basename $0) <IMAGE_NAME> <CONTAINER_NAME>"
    exit 1
fi

imagename=$1
contname=$2

(set -x; docker run -d --name $contname --hostname $contname $imagename)

echo -n "ip: "
docker inspect -f "{{ .NetworkSettings.IPAddress }}" $contname
