#!/bin/bash
set -e

if [[ -z $1 ]]; then
    echo "USAGE: $(basename $0) <container_name>"
    exit 1
fi

CONT_NAME=$1

read -r -p "Going to stop and remove ${CONT_NAME}? [y/n] " choice
if [[ ${choice} =~ ^[Yy]$ ]]; then
    set -x
    sudo docker stop ${CONT_NAME}
    sudo docker rm ${CONT_NAME}
fi
