#!/bin/bash
set -e

function usage {
cat << EOF
USAGE
    $(basename $0) <url>

DESCRIPTION
    Check webserver header
EOF
}

[[ $1 == '-h' || $1 == '--help' ]] && usage && exit 0
[[ ! $1 ]] && usage && exit 1

curl -I $@
