#!/bin/bash
set -e

if [[ $# != 4 ]]; then
cat << EOF
  USAGE
    tn <user@remote_host> <remote_port> <local_host> <local_port>

  DESCRIPTION
    Wrapper for ssh tunnel

  EXAMPLES

  Browse CUPS Admin on http://localhost:9631
  $ tn administrator@172.16.100.154 631 localhost 9631

  Connect remote MySQL locally with 'mysql --protocol=TCP --port=3333'
  $ tn user@remote 3306 localhost 3333
EOF
  exit 1
fi

remote_host=$1
remote_port=$2
local_host=$3
local_port=$4

echo ssh $remote_host -T -L $local_port:$local_host:$remote_port
ssh $remote_host -T -L $local_port:$local_host:$remote_port
