#!/bin/bash
set -e

function usage {
cat << EOF
USAGE
    ${0##*/} [-nd] [-e EXCLUDE_LIST] [-p PORT] [USER@]HOST:SRC DEST
    ${0##*/} [-nd] [-e EXCLUDE_LIST] [-p PORT] SRC [USER@]HOST:DEST

DESCRIPTION
    Wrapper around rsync

    -n              Dry run ('--dry-run' option)
    -d              Delete dest files if not found on src ('--delete' option)
    -e EXCLUDE_LIST Exclude list (the value of '--exclude' option)
    -p PORT         Optional (default to 22)
EOF
}

PORT=22

while getopts :nde:p: FLAG; do
    case $FLAG in
        n)
            DRYRUN_OPTION="-n"
            ;;
        d)
            DELETE_OPTION="--delete"
            ;;
        e)
            EXCLUDE_OPTION="--exclude=\"$OPTARG\""
            ;;
        p)
            PORT="$OPTARG"
            ;;
        ?)
            usage
            exit 0
            ;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [[ $# != 2 ]]; then
    usage
    exit 1
fi

SRC=$1
DEST=$2

rsync ${DRYRUN_OPTION} ${DELETE_OPTION} -azhvP --rsh="ssh -p ${PORT}" ${EXCLUDE_OPTION} ${SRC} ${DEST}
