#!/bin/bash
set -e

if [[ -z $1 ]]; then
    echo "Usage: $(basename $0) <command>"
    exit 1
fi

# Based on: http://www.commandlinefu.com/commands/view/9594/find-out-which-debian-package-a-command-executable-belongs-to-on-debian-based-distros
readlink -f "$(which $1)" | xargs --no-run-if-empty dpkg -S;

